language: python

sudo: required
dist: trusty

python:
  - "2.7"
  - "3.5"

git:
  submodules: false

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libgdal1h
      - libgdal1-dev
      - libgeos-dev
      - devscripts
      - debhelper
      - python-setuptools

# Handle Git submodules yourself
git:
    submodules: false

install:
  - pip install pip --upgrade
  - pip install .
  - pip install -r requirements-gdal.txt
  - pip install coveralls

script:
  - python -m unittest tests
  - coverage run --source=pywps -m unittest tests

after_success:
  - coveralls
  - debuild -b -uc -us

# whitelist
branches:
  only:
    - master
